server:
  port: 8761

spring:
  application:
    name: discovery-server

eureka:
  instance:
    hostname: ${DISCOVERY_SERVER_HOSTNAME:localhost}
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0

management:
  server:
    port: 9761